export const FETCH_INSPECTIONS = 'FETCH_INSPECTIONS';
export const FETCH_INSPECTIONS_SUCCESS = 'FETCH_INSPECTIONS_SUCCESS';
export const FETCH_INSPECTIONS_FAILURE = 'FETCH_INSPECTIONS_FAILURE';
export const ADD_INSPECTION = 'ADD_INSPECTION';

export const UPDATE_INSPECTION = 'UPDATE_INSPECTION';
export const UPDATE_INSPECTION_SUCCESS = 'UPDATE_INSPECTION_SUCCESS';
export const UPDATE_INSPECTION_FAILURE = 'UPDATE_INSPECTION_FAILURE';